export const APPLICATION_STATUSES = [
	"DRAFT",
	"APPLIED",
	"SCREENING",
	"INTERVIEW",
	"OFFER",
	"REJECTED",
	"WITHDRAWN"
];

export const APPLICATION_SOURCES = [
	"LINKEDIN",
	"WELCOME_TO_THE_JUNGLE",
	"INDEED",
	"COMPANY_WEBSITE",
	"OTHER"
];